import { constantGlobalStyle } from './constantGlobalStyle';
import { ThemeConfigType } from './types';
import { extractColorVariables } from './utils';

/**
 * Pure, dependency-free helpers that turn grauity's design tokens into CSS.
 *
 * Used in two places so the runtime and the shipped static CSS can never drift:
 *  - `GlobalStyle` (runtime) consumes `buildThemeVariables`.
 *  - `scripts/build-tokens.ts` (build time) consumes `buildTokensCss` +
 *    `buildTailwindThemeCss` to emit `dist/css/tokens.css` and
 *    `dist/css/grauity-theme.css`.
 */

/** camelCase -> kebab-case, e.g. `bgActionBrandHover` -> `bg-action-brand-hover`. */
export const camelToKebab = (key: string): string =>
    key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/**
 * CSS custom-property declarations for a single theme: the structured semantic
 * colours (`--bg-*`/`--text-*`/`--border-*`) plus the flat legacy colour
 * aliases and visibility flags. Mirrors exactly what `GlobalStyle` injects per
 * `.grauity-theme-*` scope.
 */
export const buildThemeVariables = (theme: ThemeConfigType): string => {
    const lines: string[] = [];

    // Structured semantic colours -> --bg-*, --text-*, --border-*
    extractColorVariables(theme.colors).forEach((line) =>
        lines.push(String(line))
    );

    // Flat legacy colour aliases (text / background / border) keyed by camelCase.
    const legacy = (theme.legacyColors ?? {}) as Record<
        string,
        Record<string, string>
    >;
    Object.values(legacy).forEach((group) => {
        Object.entries(group ?? {}).forEach(([key, value]) => {
            if (value) {
                lines.push(`--${camelToKebab(key)}: ${value};`);
            }
        });
    });

    // Visibility flags (e.g. --light-visible / --dark-visible).
    const visibility = (theme.visibility ?? {}) as Record<string, string>;
    Object.entries(visibility).forEach(([key, value]) => {
        if (value) {
            lines.push(`--${camelToKebab(key)}: ${value};`);
        }
    });

    return lines.join('\n');
};

const indentBlock = (block: string, pad = '    '): string =>
    block
        .split('\n')
        .map((line) => (line.trim() ? pad + line.trim() : ''))
        .join('\n')
        .replace(/\n{2,}/g, '\n');

export interface ThemeConfigMap {
    light: ThemeConfigType;
    dark: ThemeConfigType;
}

const AUTOGEN_BANNER = `/*
 * AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand.
 * Source of truth: ui/themes/constantGlobalStyle.ts + {light,dark}ThemeConstants.ts
 */`;

/**
 * The full static token stylesheet (zero-runtime alternative to <GlobalStyle/>):
 *  - primitives at :root
 *  - light semantic at :root + .grauity-theme-light (sensible default)
 *  - dark semantic at .dark + .grauity-theme-dark (Tailwind and grauity scopes)
 */
export const buildTokensCss = ({ light, dark }: ThemeConfigMap): string => {
    return `${AUTOGEN_BANNER}

:root {
${indentBlock(constantGlobalStyle)}
}

:root,
.grauity-theme-light {
${indentBlock(buildThemeVariables(light))}
}

.dark,
.grauity-theme-dark {
${indentBlock(buildThemeVariables(dark))}
}
`;
};

// ---------------------------------------------------------------------------
// Tailwind v4 @theme export
// ---------------------------------------------------------------------------

interface Pair {
    name: string;
    value: string;
}

/** Parse `--name: value;` declarations out of the primitives block, in order. */
const parsePrimitives = (css: string): Pair[] => {
    const pairs: Pair[] = [];
    const re = /--([\w-]+)\s*:\s*([^;]+);/g;
    let match = re.exec(css);
    while (match !== null) {
        pairs.push({ name: match[1].trim(), value: match[2].trim() });
        match = re.exec(css);
    }
    return pairs;
};

/**
 * Resolve `var(--x, fallback)` references against the primitive map so the
 * Tailwind theme is self-contained (no dependency on tokens.css).
 */
const makeResolver = (map: Map<string, string>) => {
    const resolve = (value: string, depth = 0): string => {
        if (depth > 5) {
            return value;
        }
        const varMatch = value.match(
            /^var\(\s*--([\w-]+)\s*(?:,\s*([^)]+))?\)$/
        );
        if (!varMatch) {
            return value;
        }
        const [, ref, fallback] = varMatch;
        if (map.has(ref)) {
            return resolve(map.get(ref) as string, depth + 1);
        }
        return (fallback ?? value).trim();
    };
    return resolve;
};

/**
 * Map a grauity primitive name to a Tailwind v4 `@theme` namespace, or null to
 * skip. We KEEP the `px`/`percent` suffix on spacing/radius/text so they don't
 * collide with Tailwind's numeric scales and stay 1:1 with Figma token names.
 */
const toTailwindName = (name: string): string | null => {
    if (
        /^(neutral|brand|error|success|warning|yellow|purple|alpha)-/.test(name)
    ) {
        return `--color-${name}`;
    }
    if (name.startsWith('spacing-')) {
        return `--${name}`; // --spacing-16px -> p-16px
    }
    if (name.startsWith('corner-radius-')) {
        return `--radius-${name.slice('corner-radius-'.length)}`;
    }
    if (name.startsWith('font-size-')) {
        return `--text-${name.slice('font-size-'.length)}`;
    }
    if (name.startsWith('font-weight-')) {
        return `--${name}`; // --font-weight-550 -> font-550
    }
    // Intentionally skipped: font-family (font adoption decided separately),
    // backdrop-blur (blur() values aren't Tailwind --blur length tokens),
    // z-index (no Tailwind theme namespace).
    return null;
};

/**
 * Emit a Tailwind v4 `@theme` block from grauity primitives, with values
 * resolved inline so it is self-contained. Generates utilities such as
 * `bg-brand-500`, `p-16px`, `rounded-8px`, `text-16px`, `font-550`.
 */
export const buildTailwindThemeCss = (): string => {
    const primitives = parsePrimitives(constantGlobalStyle);
    const map = new Map(primitives.map((p) => [p.name, p.value]));
    const resolve = makeResolver(map);

    const lines: string[] = [];
    primitives.forEach(({ name, value }) => {
        const twName = toTailwindName(name);
        if (!twName) {
            return;
        }
        lines.push(`    ${twName}: ${resolve(value)};`);
    });

    return `${AUTOGEN_BANNER}

@theme {
${lines.join('\n')}
}
`;
};
