export const ICON_TAGS = {
    'exclamation-circle-filled': ['Alert'],
    'exclamation-circle': ['Alert'],
    'exclamation-triangle-filled': ['Alert'],
    'exclamation-triangle': ['Alert'],
    'info-circle-filled': ['Alert'],
    'info-circle': ['Alert'],
    'question-circle-filled': ['Alert'],
    'question-circle': ['Alert'],
    'code-alt-filled': ['Code'],
    'code-alt': ['Code'],
    'code-filled': ['Code'],
    code: ['Code'],
    'project-filled': ['Code'],
    project: ['Code'],
    'terminal-filled': ['Code'],
    terminal: ['Code'],
    'nst-filled': ['College'],
    nst: ['College'],
    'desktop-filled': ['Device'],
    desktop: ['Device'],
    'gamepad-filled': ['Device'],
    gamepad: ['Device'],
    'lamp-filled': ['Device'],
    lamp: ['Device'],
    'laptop-filled': ['Device'],
    laptop: ['Device'],
    'mobile-filled': ['Device'],
    mobile: ['Device'],
    'archive-filled': ['Docs'],
    archive: ['Docs'],
    'bookmark-filled': ['Docs'],
    bookmark: ['Docs'],
    'file-alt-filled': ['Docs'],
    'file-alt': ['Docs'],
    'file-filled': ['Docs'],
    'file-lightning-filled': ['Docs'],
    'file-lightning': ['Docs'],
    file: ['Docs'],
    'folder-filled': ['Docs'],
    'folder-open-filled': ['Docs'],
    'folder-open': ['Docs'],
    folder: ['Docs'],
    'label-filled': ['Docs'],
    label: ['Docs'],
    'note-filled': ['Docs'],
    note: ['Docs'],
    'pen-filled': ['Docs'],
    pen: ['Docs'],
    'pin-filled': ['Docs'],
    pin: ['Docs'],
    'currency-filled': ['Finance'],
    'currency-rupee-filled': ['Finance'],
    'currency-rupee': ['Finance'],
    currency: ['Finance'],
    'eye-off-filled': ['Media'],
    'eye-off': ['Media'],
    'eye-on-filled': ['Media'],
    'eye-on': ['Media'],
    'headphone-filled': ['Media'],
    'headphone-mic-filled': ['Media'],
    'headphone-mic': ['Media'],
    headphone: ['Media'],
    'mic-filled': ['Media'],
    mic: ['Media'],
    'micmute-filled': ['Media'],
    micmute: ['Media'],
    'pause-circle-filled': ['Media'],
    'pause-circle': ['Media'],
    'pause-filled': ['Media'],
    pause: ['Media'],
    'play-circle-filled': ['Media'],
    'play-circle': ['Media'],
    'play-filled': ['Media'],
    'play-rectangle-filled': ['Media'],
    'play-rectangle': ['Media'],
    play: ['Media'],
    'skip-next-filled': ['Media'],
    'skip-next': ['Media'],
    'skip-previous-filled': ['Media'],
    'skip-previous': ['Media'],
    'video-filled': ['Media'],
    'video-off-filled': ['Media'],
    'video-off': ['Media'],
    video: ['Media'],
    'volume-maximum-filled': ['Media'],
    'volume-maximum': ['Media'],
    'volume-minimum-filled': ['Media'],
    'volume-minimum': ['Media'],
    'volume-mute-filled': ['Media'],
    'volume-mute': ['Media'],
    'waveform-filled': ['Media'],
    waveform: ['Media'],
    'comment-filled': ['Misc'],
    comment: ['Misc'],
    'confetti-filled': ['Misc'],
    confetti: ['Misc'],
    'connector-filled': ['Misc'],
    connector: ['Misc'],
    'doubt-alt2-filled': ['Misc'],
    'doubt-alt2': ['Misc'],
    'doubt-filled': ['Misc'],
    'doubt-message-filled': ['Misc'],
    'doubt-message': ['Misc'],
    doubt: ['Misc'],
    'fire-filled': ['Misc'],
    fire: ['Misc'],
    'hearing-filled': ['Misc'],
    hearing: ['Misc'],
    'heart-filled': ['Misc'],
    heart: ['Misc'],
    'hearthands-filled': ['Misc'],
    hearthands: ['Misc'],
    'lock-filled': ['Misc'],
    'lock-open-filled': ['Misc'],
    'lock-open': ['Misc'],
    lock: ['Misc'],
    'magic-orb-filled': ['Misc'],
    'magic-orb': ['Misc'],
    'message-filled': ['Misc'],
    'message-info-filled': ['Misc'],
    'message-info': ['Misc'],
    message: ['Misc'],
    'milestone-filled': ['Misc'],
    milestone: ['Misc'],
    'scholar-hat-filled': ['Misc'],
    'scholar-hat': ['Misc'],
    'smiley-bad-filled': ['Misc'],
    'smiley-bad': ['Misc'],
    'smiley-filled': ['Misc'],
    'smiley-happy-filled': ['Misc'],
    'smiley-happy': ['Misc'],
    'smiley-neutral-filled': ['Misc'],
    'smiley-neutral': ['Misc'],
    'smiley-sad-filled': ['Misc'],
    'smiley-sad': ['Misc'],
    'smiley-very-bad-filled': ['Misc'],
    'smiley-very-bad': ['Misc'],
    'smiley-very-happy-filled': ['Misc'],
    'smiley-very-happy': ['Misc'],
    smiley: ['Misc'],
    'spark-filled': ['Misc'],
    spark: ['Misc'],
    'sparkle-filled': ['Misc'],
    sparkle: ['Misc'],
    'target-filled': ['Misc'],
    target: ['Misc'],
    'check-badge-filled': ['Reward'],
    'check-badge': ['Reward'],
    'crown-filled': ['Reward'],
    crown: ['Reward'],
    'flag-filled': ['Reward'],
    flag: ['Reward'],
    'gift-filled': ['Reward'],
    gift: ['Reward'],
    'leaderboard-filled': ['Reward'],
    leaderboard: ['Reward'],
    'medal-filled': ['Reward'],
    medal: ['Reward'],
    'star-filled': ['Reward'],
    'star-half-filled': ['Reward'],
    'star-half': ['Reward'],
    star: ['Reward'],
    'trophy-filled': ['Reward'],
    trophy: ['Reward'],
    codechef: ['Social'],
    codeforces: ['Social'],
    facebook: ['Social'],
    github: ['Social'],
    'google-doc': ['Social'],
    'google-slides': ['Social'],
    google: ['Social'],
    hackerearth: ['Social'],
    hackerrank: ['Social'],
    instagram: ['Social'],
    kaggle: ['Social'],
    leetcode: ['Social'],
    linkedin: ['Social'],
    twitter: ['Social'],
    whatsapp: ['Social'],
    x: ['Social'],
    youtube: ['Social'],
    'ai-summary-filled': ['System'],
    'ai-summary': ['System'],
    'arrow-double-filled': ['System'],
    'arrow-double': ['System'],
    'arrow-down-filled': ['System'],
    'arrow-down-left-filled': ['System'],
    'arrow-down-left': ['System'],
    'arrow-down-right-filled': ['System'],
    'arrow-down-right': ['System'],
    'arrow-down': ['System'],
    'arrow-left-filled': ['System'],
    'arrow-left': ['System'],
    'arrow-right-filled': ['System'],
    'arrow-right': ['System'],
    'arrow-up-filled': ['System'],
    'arrow-up-left-filled': ['System'],
    'arrow-up-left': ['System'],
    'arrow-up-right-filled': ['System'],
    'arrow-up-right': ['System'],
    'arrow-up': ['System'],
    'ban-filled': ['System'],
    ban: ['System'],
    'bin-filled': ['System'],
    bin: ['System'],
    'book-alt-filled': ['System'],
    'book-alt': ['System'],
    'book-alt2-filled': ['System'],
    'book-alt2': ['System'],
    'book-alt3-filled': ['System'],
    'book-alt3': ['System'],
    'book-filled': ['System'],
    'book-open-filled': ['System'],
    'book-open': ['System'],
    book: ['System'],
    'briefcase-alt2-filled': ['System'],
    'briefcase-alt2': ['System'],
    'briefcase-filled': ['System'],
    briefcase: ['System'],
    'broadcast-filled': ['System'],
    broadcast: ['System'],
    'bug-filled': ['System'],
    bug: ['System'],
    'bulb-filled': ['System'],
    bulb: ['System'],
    'call-end-filled': ['System'],
    'call-end': ['System'],
    'call-start-filled': ['System'],
    'call-start': ['System'],
    'camera-filled': ['System'],
    camera: ['System'],
    'caret-double-filled': ['System'],
    'caret-double': ['System'],
    'caret-down-filled': ['System'],
    'caret-down': ['System'],
    'caret-left-filled': ['System'],
    'caret-left': ['System'],
    'caret-right-filled': ['System'],
    'caret-right': ['System'],
    'caret-up-filled': ['System'],
    'caret-up': ['System'],
    'check-circle-filled': ['System'],
    'check-circle': ['System'],
    'check-filled': ['System'],
    'check-square-filled': ['System'],
    'check-square': ['System'],
    check: ['System'],
    'chevron-down-double-filled': ['System'],
    'chevron-down-double': ['System'],
    'chevron-down-filled': ['System'],
    'chevron-down': ['System'],
    'chevron-left-double-filled': ['System'],
    'chevron-left-double': ['System'],
    'chevron-left-filled': ['System'],
    'chevron-left': ['System'],
    'chevron-right-double-filled': ['System'],
    'chevron-right-double': ['System'],
    'chevron-right-filled': ['System'],
    'chevron-right': ['System'],
    'chevron-up-double-filled': ['System'],
    'chevron-up-double': ['System'],
    'chevron-up-filled': ['System'],
    'chevron-up': ['System'],
    'circle-filled': ['System'],
    circle: ['System'],
    'clock-alarm-filled': ['System'],
    'clock-alarm': ['System'],
    'close-circle-filled': ['System'],
    'close-circle': ['System'],
    'close-filled': ['System'],
    'close-square-filled': ['System'],
    'close-square': ['System'],
    close: ['System'],
    'compass-filled': ['System'],
    compass: ['System'],
    'copy-filled': ['System'],
    copy: ['System'],
    'database-filled': ['System'],
    database: ['System'],
    'diamond-filled': ['System'],
    diamond: ['System'],
    'dot-circle-filled': ['System'],
    'dot-circle': ['System'],
    'double-check-filled': ['System'],
    'double-check': ['System'],
    'download-filled': ['System'],
    download: ['System'],
    'eda-filled': ['System'],
    eda: ['System'],
    'email-alt-filled': ['System'],
    'email-alt': ['System'],
    'email-filled': ['System'],
    email: ['System'],
    'filter-filled': ['System'],
    filter: ['System'],
    'floppy-filled': ['System'],
    floppy: ['System'],
    'forward-filled': ['System'],
    forward: ['System'],
    'gear-filled': ['System'],
    gear: ['System'],
    'git-commit-filled': ['System'],
    'git-commit': ['System'],
    'globe-filled': ['System'],
    globe: ['System'],
    'grip-hortizontal-filled': ['System'],
    'grip-hortizontal': ['System'],
    'grip-vertical-filled': ['System'],
    'grip-vertical': ['System'],
    'growth-down-filled': ['System'],
    'growth-down': ['System'],
    'growth-up-filled': ['System'],
    'growth-up': ['System'],
    'help-filled': ['System'],
    help: ['System'],
    'hold-filled': ['System'],
    hold: ['System'],
    'home-filled': ['System'],
    home: ['System'],
    'hourglass-filled': ['System'],
    hourglass: ['System'],
    'kebab-horizontal-filled': ['System'],
    'kebab-horizontal': ['System'],
    'kebab-vertical-filled': ['System'],
    'kebab-vertical': ['System'],
    'link-filled': ['System'],
    link: ['System'],
    'list-checked-filled': ['System'],
    'list-checked': ['System'],
    'list-filled': ['System'],
    list: ['System'],
    'load-filled': ['System'],
    load: ['System'],
    'loading-filled': ['System'],
    loading: ['System'],
    'loudspeaker-filled': ['System'],
    loudspeaker: ['System'],
    'machine-learning-filled': ['System'],
    'machine-learning': ['System'],
    'map-pin-alt1-filled': ['System'],
    'map-pin-alt1': ['System'],
    'map-pin-alt2-filled': ['System'],
    'map-pin-alt2': ['System'],
    'map-pin-filled': ['System'],
    'map-pin': ['System'],
    'maximize-filled': ['System'],
    maximize: ['System'],
    'meeting-room-filled': ['System'],
    'meeting-room': ['System'],
    'menu-alt2-filled': ['System'],
    'menu-alt2': ['System'],
    'menu-filled': ['System'],
    'menu-grid-filled': ['System'],
    'menu-grid': ['System'],
    menu: ['System'],
    'microchip-filled': ['System'],
    microchip: ['System'],
    'minimize-filled': ['System'],
    minimize: ['System'],
    'minus-circle-filled': ['System'],
    'minus-circle': ['System'],
    'minus-square-filled': ['System'],
    'minus-square': ['System'],
    'moon-filled': ['System'],
    moon: ['System'],
    'new-tab-filled': ['System'],
    'new-tab': ['System'],
    'paper-clip-filled': ['System'],
    'paper-clip': ['System'],
    'plus-circle-filled': ['System'],
    'plus-circle': ['System'],
    'plus-filled': ['System'],
    'plus-square-filled': ['System'],
    'plus-square': ['System'],
    plus: ['System'],
    'power-bi-filled': ['System'],
    'power-bi': ['System'],
    'printer-filled': ['System'],
    printer: ['System'],
    'progress-half-filled': ['System'],
    'progress-half': ['System'],
    'progress-quarter-filled': ['System'],
    'progress-quarter': ['System'],
    'progress-zero-filled': ['System'],
    'progress-zero': ['System'],
    'python-filled': ['System'],
    python: ['System'],
    'question-filled': ['System'],
    question: ['System'],
    'quiz-filled': ['System'],
    quiz: ['System'],
    'refresh-filled': ['System'],
    refresh: ['System'],
    'remove-filled': ['System'],
    remove: ['System'],
    'reply-filled': ['System'],
    reply: ['System'],
    'retail-filled': ['System'],
    retail: ['System'],
    'screen-share-filled': ['System'],
    'screen-share': ['System'],
    'screenshare-start-filled': ['System'],
    'screenshare-start': ['System'],
    'screenshare-stop-filled': ['System'],
    'screenshare-stop': ['System'],
    'search-filled': ['System'],
    search: ['System'],
    'share-filled': ['System'],
    share: ['System'],
    'shield-alert-filled': ['System'],
    'shield-alert': ['System'],
    'shield-check-filled': ['System'],
    'shield-check': ['System'],
    'shield-filled': ['System'],
    'shield-lock-filled': ['System'],
    'shield-lock': ['System'],
    'shield-x-filled': ['System'],
    'shield-x': ['System'],
    shield: ['System'],
    'shop-filled': ['System'],
    shop: ['System'],
    'sidebar-left-filled': ['System'],
    'sidebar-left': ['System'],
    'sidebar-right-filled': ['System'],
    'sidebar-right': ['System'],
    'signin-filled': ['System'],
    signin: ['System'],
    'signout-filled': ['System'],
    signout: ['System'],
    'slider-filled': ['System'],
    slider: ['System'],
    'split-screen-filled': ['System'],
    'split-screen': ['System'],
    'square-filled': ['System'],
    square: ['System'],
    'sticky-note-filled': ['System'],
    'sticky-note': ['System'],
    'sun-filled': ['System'],
    sun: ['System'],
    'thumbs-down-filled': ['System'],
    'thumbs-down': ['System'],
    'thumbs-up-filled': ['System'],
    'thumbs-up': ['System'],
    'thunder-filled': ['System'],
    thunder: ['System'],
    'transcript-filled': ['System'],
    transcript: ['System'],
    'truck-filled': ['System'],
    truck: ['System'],
    'upload-filled': ['System'],
    upload: ['System'],
    'wrench-filled': ['System'],
    wrench: ['System'],
    'bell-filled': ['Time'],
    bell: ['Time'],
    'calender-check-filled': ['Time'],
    'calender-check': ['Time'],
    'calender-filled': ['Time'],
    'calender-plus-filled': ['Time'],
    'calender-plus': ['Time'],
    calender: ['Time'],
    'clock-filled': ['Time'],
    clock: ['Time'],
    'rewatch-filled': ['Time'],
    rewatch: ['Time'],
    'stopwatch-filled': ['Time'],
    stopwatch: ['Time'],
    'bot-filled': ['User'],
    bot: ['User'],
    'person-check-filled': ['User'],
    'person-check': ['User'],
    'person-filled': ['User'],
    'person-plus-filled': ['User'],
    'person-plus': ['User'],
    person: ['User'],
    'user-speak-filled': ['User'],
    'user-speak': ['User'],
    'users-filled': ['User'],
    users: ['User'],
};
export const TAG_ICONS = {
    Alert: [
        'exclamation-circle-filled',
        'exclamation-circle',
        'exclamation-triangle-filled',
        'exclamation-triangle',
        'info-circle-filled',
        'info-circle',
        'question-circle-filled',
        'question-circle',
    ],
    Code: [
        'code-alt-filled',
        'code-alt',
        'code-filled',
        'code',
        'project-filled',
        'project',
        'terminal-filled',
        'terminal',
    ],
    College: ['nst-filled', 'nst'],
    Device: [
        'desktop-filled',
        'desktop',
        'gamepad-filled',
        'gamepad',
        'lamp-filled',
        'lamp',
        'laptop-filled',
        'laptop',
        'mobile-filled',
        'mobile',
    ],
    Docs: [
        'archive-filled',
        'archive',
        'bookmark-filled',
        'bookmark',
        'file-alt-filled',
        'file-alt',
        'file-filled',
        'file-lightning-filled',
        'file-lightning',
        'file',
        'folder-filled',
        'folder-open-filled',
        'folder-open',
        'folder',
        'label-filled',
        'label',
        'note-filled',
        'note',
        'pen-filled',
        'pen',
        'pin-filled',
        'pin',
    ],
    Finance: [
        'currency-filled',
        'currency-rupee-filled',
        'currency-rupee',
        'currency',
    ],
    Media: [
        'eye-off-filled',
        'eye-off',
        'eye-on-filled',
        'eye-on',
        'headphone-filled',
        'headphone-mic-filled',
        'headphone-mic',
        'headphone',
        'mic-filled',
        'mic',
        'micmute-filled',
        'micmute',
        'pause-circle-filled',
        'pause-circle',
        'pause-filled',
        'pause',
        'play-circle-filled',
        'play-circle',
        'play-filled',
        'play-rectangle-filled',
        'play-rectangle',
        'play',
        'skip-next-filled',
        'skip-next',
        'skip-previous-filled',
        'skip-previous',
        'video-filled',
        'video-off-filled',
        'video-off',
        'video',
        'volume-maximum-filled',
        'volume-maximum',
        'volume-minimum-filled',
        'volume-minimum',
        'volume-mute-filled',
        'volume-mute',
        'waveform-filled',
        'waveform',
    ],
    Misc: [
        'comment-filled',
        'comment',
        'confetti-filled',
        'confetti',
        'connector-filled',
        'connector',
        'doubt-alt2-filled',
        'doubt-alt2',
        'doubt-filled',
        'doubt-message-filled',
        'doubt-message',
        'doubt',
        'fire-filled',
        'fire',
        'hearing-filled',
        'hearing',
        'heart-filled',
        'heart',
        'hearthands-filled',
        'hearthands',
        'lock-filled',
        'lock-open-filled',
        'lock-open',
        'lock',
        'magic-orb-filled',
        'magic-orb',
        'message-filled',
        'message-info-filled',
        'message-info',
        'message',
        'milestone-filled',
        'milestone',
        'scholar-hat-filled',
        'scholar-hat',
        'smiley-bad-filled',
        'smiley-bad',
        'smiley-filled',
        'smiley-happy-filled',
        'smiley-happy',
        'smiley-neutral-filled',
        'smiley-neutral',
        'smiley-sad-filled',
        'smiley-sad',
        'smiley-very-bad-filled',
        'smiley-very-bad',
        'smiley-very-happy-filled',
        'smiley-very-happy',
        'smiley',
        'spark-filled',
        'spark',
        'sparkle-filled',
        'sparkle',
        'target-filled',
        'target',
    ],
    Reward: [
        'check-badge-filled',
        'check-badge',
        'crown-filled',
        'crown',
        'flag-filled',
        'flag',
        'gift-filled',
        'gift',
        'leaderboard-filled',
        'leaderboard',
        'medal-filled',
        'medal',
        'star-filled',
        'star-half-filled',
        'star-half',
        'star',
        'trophy-filled',
        'trophy',
    ],
    Social: [
        'codechef',
        'codeforces',
        'facebook',
        'github',
        'google-doc',
        'google-slides',
        'google',
        'hackerearth',
        'hackerrank',
        'instagram',
        'kaggle',
        'leetcode',
        'linkedin',
        'twitter',
        'whatsapp',
        'x',
        'youtube',
    ],
    System: [
        'ai-summary-filled',
        'ai-summary',
        'arrow-double-filled',
        'arrow-double',
        'arrow-down-filled',
        'arrow-down-left-filled',
        'arrow-down-left',
        'arrow-down-right-filled',
        'arrow-down-right',
        'arrow-down',
        'arrow-left-filled',
        'arrow-left',
        'arrow-right-filled',
        'arrow-right',
        'arrow-up-filled',
        'arrow-up-left-filled',
        'arrow-up-left',
        'arrow-up-right-filled',
        'arrow-up-right',
        'arrow-up',
        'ban-filled',
        'ban',
        'bin-filled',
        'bin',
        'book-alt-filled',
        'book-alt',
        'book-alt2-filled',
        'book-alt2',
        'book-alt3-filled',
        'book-alt3',
        'book-filled',
        'book-open-filled',
        'book-open',
        'book',
        'briefcase-alt2-filled',
        'briefcase-alt2',
        'briefcase-filled',
        'briefcase',
        'broadcast-filled',
        'broadcast',
        'bug-filled',
        'bug',
        'bulb-filled',
        'bulb',
        'call-end-filled',
        'call-end',
        'call-start-filled',
        'call-start',
        'camera-filled',
        'camera',
        'caret-double-filled',
        'caret-double',
        'caret-down-filled',
        'caret-down',
        'caret-left-filled',
        'caret-left',
        'caret-right-filled',
        'caret-right',
        'caret-up-filled',
        'caret-up',
        'check-circle-filled',
        'check-circle',
        'check-filled',
        'check-square-filled',
        'check-square',
        'check',
        'chevron-down-double-filled',
        'chevron-down-double',
        'chevron-down-filled',
        'chevron-down',
        'chevron-left-double-filled',
        'chevron-left-double',
        'chevron-left-filled',
        'chevron-left',
        'chevron-right-double-filled',
        'chevron-right-double',
        'chevron-right-filled',
        'chevron-right',
        'chevron-up-double-filled',
        'chevron-up-double',
        'chevron-up-filled',
        'chevron-up',
        'circle-filled',
        'circle',
        'clock-alarm-filled',
        'clock-alarm',
        'close-circle-filled',
        'close-circle',
        'close-filled',
        'close-square-filled',
        'close-square',
        'close',
        'compass-filled',
        'compass',
        'copy-filled',
        'copy',
        'database-filled',
        'database',
        'diamond-filled',
        'diamond',
        'dot-circle-filled',
        'dot-circle',
        'double-check-filled',
        'double-check',
        'download-filled',
        'download',
        'eda-filled',
        'eda',
        'email-alt-filled',
        'email-alt',
        'email-filled',
        'email',
        'filter-filled',
        'filter',
        'floppy-filled',
        'floppy',
        'forward-filled',
        'forward',
        'gear-filled',
        'gear',
        'git-commit-filled',
        'git-commit',
        'globe-filled',
        'globe',
        'grip-hortizontal-filled',
        'grip-hortizontal',
        'grip-vertical-filled',
        'grip-vertical',
        'growth-down-filled',
        'growth-down',
        'growth-up-filled',
        'growth-up',
        'help-filled',
        'help',
        'hold-filled',
        'hold',
        'home-filled',
        'home',
        'hourglass-filled',
        'hourglass',
        'kebab-horizontal-filled',
        'kebab-horizontal',
        'kebab-vertical-filled',
        'kebab-vertical',
        'link-filled',
        'link',
        'list-checked-filled',
        'list-checked',
        'list-filled',
        'list',
        'load-filled',
        'load',
        'loading-filled',
        'loading',
        'loudspeaker-filled',
        'loudspeaker',
        'machine-learning-filled',
        'machine-learning',
        'map-pin-alt1-filled',
        'map-pin-alt1',
        'map-pin-alt2-filled',
        'map-pin-alt2',
        'map-pin-filled',
        'map-pin',
        'maximize-filled',
        'maximize',
        'meeting-room-filled',
        'meeting-room',
        'menu-alt2-filled',
        'menu-alt2',
        'menu-filled',
        'menu-grid-filled',
        'menu-grid',
        'menu',
        'microchip-filled',
        'microchip',
        'minimize-filled',
        'minimize',
        'minus-circle-filled',
        'minus-circle',
        'minus-square-filled',
        'minus-square',
        'moon-filled',
        'moon',
        'new-tab-filled',
        'new-tab',
        'paper-clip-filled',
        'paper-clip',
        'plus-circle-filled',
        'plus-circle',
        'plus-filled',
        'plus-square-filled',
        'plus-square',
        'plus',
        'power-bi-filled',
        'power-bi',
        'printer-filled',
        'printer',
        'progress-half-filled',
        'progress-half',
        'progress-quarter-filled',
        'progress-quarter',
        'progress-zero-filled',
        'progress-zero',
        'python-filled',
        'python',
        'question-filled',
        'question',
        'quiz-filled',
        'quiz',
        'refresh-filled',
        'refresh',
        'remove-filled',
        'remove',
        'reply-filled',
        'reply',
        'retail-filled',
        'retail',
        'screen-share-filled',
        'screen-share',
        'screenshare-start-filled',
        'screenshare-start',
        'screenshare-stop-filled',
        'screenshare-stop',
        'search-filled',
        'search',
        'share-filled',
        'share',
        'shield-alert-filled',
        'shield-alert',
        'shield-check-filled',
        'shield-check',
        'shield-filled',
        'shield-lock-filled',
        'shield-lock',
        'shield-x-filled',
        'shield-x',
        'shield',
        'shop-filled',
        'shop',
        'sidebar-left-filled',
        'sidebar-left',
        'sidebar-right-filled',
        'sidebar-right',
        'signin-filled',
        'signin',
        'signout-filled',
        'signout',
        'slider-filled',
        'slider',
        'split-screen-filled',
        'split-screen',
        'square-filled',
        'square',
        'sticky-note-filled',
        'sticky-note',
        'sun-filled',
        'sun',
        'thumbs-down-filled',
        'thumbs-down',
        'thumbs-up-filled',
        'thumbs-up',
        'thunder-filled',
        'thunder',
        'transcript-filled',
        'transcript',
        'truck-filled',
        'truck',
        'upload-filled',
        'upload',
        'wrench-filled',
        'wrench',
    ],
    Time: [
        'bell-filled',
        'bell',
        'calender-check-filled',
        'calender-check',
        'calender-filled',
        'calender-plus-filled',
        'calender-plus',
        'calender',
        'clock-filled',
        'clock',
        'rewatch-filled',
        'rewatch',
        'stopwatch-filled',
        'stopwatch',
    ],
    User: [
        'bot-filled',
        'bot',
        'person-check-filled',
        'person-check',
        'person-filled',
        'person-plus-filled',
        'person-plus',
        'person',
        'user-speak-filled',
        'user-speak',
        'users-filled',
        'users',
    ],
};
